import { writeFile, readFile, readdir, mkdir, exists } from "node:fs/promises";
import { glob } from "glob";

const maps = await glob("*.txt", { cwd: Bun.env.GARRYSMOD + "/addonmap", absolute: true });

let files: Set<string> = new Set();
for await (const map of maps) {
    const file = await readFile(map, { encoding: "utf-8" });
    for (const line of file.split("\n")) {
        files.add(line);
    }
}

for (const file of files) {
    const fileExt = file.split(".").pop();
    if (!fileExt) {
        console.log("File has no extension?", file);
        process.exit();
    }
    if (!["vmt", "vtf", "mdl", "vvd", "ani", "vtx", "phy", "png", "jpg", "jpeg", "wav", "ogg", "mp3"].includes(fileExt))
        continue;

    if (!(await exists(`${Bun.env.GARRYSMOD}/${file}.bz2`))) {
        console.log("Compressing:", file);
        Bun.spawnSync(["bzip2", "-k", `${Bun.env.GARRYSMOD}/${file}`]);
    } else {
        console.log("Exists:", file + ".bz2");
    }
}

let script = `-- Autogenerated by cirro's addon scripts
-- Any changes made to this file will NOT be persisted

if (SERVER) then
`;
for (const file of files) {
    const fileExt = file.split(".").pop();
    if (!fileExt) {
        console.log("File has no extension?", file);
        process.exit();
    }
    if (!["vmt", "vtf", "mdl", "vvd", "ani", "vtx", "phy", "png", "jpg", "jpeg", "wav", "ogg", "mp3"].includes(fileExt))
        continue;

    script += `    resource.AddSingleFile("${file}")\n`;
}
script += "end";

try {
    await readdir(`${Bun.env.GARRYSMOD}/lua/autorun/server`);
} catch (err) {
    await mkdir(`${Bun.env.GARRYSMOD}/lua/autorun/server`, { recursive: true });
}
await writeFile(`${Bun.env.GARRYSMOD}/lua/autorun/server/fastdl.lua`, script);
console.log("Written: lua/autorun/server/fastdl.lua");
